### ISSUE TITLE
Agent cache can take arbitrarily long to expire. 

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#1941]
Currently, the timer for the agent cache is only advanced when the cache is used. 

This means that if the cache is not used, items are not expired.

It could be useful to have the agent poll the cache periodically to ensure expiry

However: take into account  that the expiry should be run on a threadpool 

Another bug that can be caused by this is that the on_delete method could be called while the object is in use. This should be prevented.

**Comment by Hugo-Inmanta** [comment]
Adressed in https://github.com/inmanta/inmanta-core/pull/7846
