### ISSUE TITLE
Many deploys can happen in a very short interval

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#2177]
After an environment was cleaned and the initial compile was done. 3 deploys happened in 30s

![2020-06-16_09-06](https://user-images.githubusercontent.com/10819/84742478-c6a49080-afb0-11ea-86e8-fc6b6cb87d63.png)

**Comment by wouterdb** [comment]
From the screenshot:

- 1 periodic deploy
- 1 periodic repair
- 1 triggered deploy (trigger due to new version)

So these are the three kinds of deploys.
If this happens often, the repair and deploy timers have to be re-tuned.

**Comment by bartv** [comment]
That is indeed the answer you always give. However I see this quite often and the splay time is set to 600. The odds are not that big.

However, the separate repair process might fix this as well.

**Comment by wouterdb** [comment]
what is the interval set to? (repair/deploy interval)

**Comment by bartv** [comment]
The defaults
![2020-06-16_12-40](https://user-images.githubusercontent.com/10819/84764822-9a980800-afce-11ea-9f5c-a0ffbc006ccb.png)

**Comment by wouterdb** [comment]
This would indeed seem to suggest something is synchronizing them.

Could you pull the agent and server logs as well?
