### ISSUE TITLE
Add support for resource grouping

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#242]
For some resources (such as packages), this would speed up of the deploy a lot

**Comment by wouterdb** [comment]
I think it will be necessary to prioritize which resource type to group first

By grouping one type of resource, other resources become a lot less groupable.

for example

```
a1 -> b1
b2 -> a2
```

Where `->` is depends on.

If we group `a` first, then `b`, we get

```
b2 -> (a1,a2) -> b1
```

first `a` then `b`

```
a1 -> (b1,b2) -> a2
```

So we should indicate ( in some way) what to pack first

**Comment by bartv** [comment]
Stale first implementation attached to this ticket from @wouterdb 
[resource-grouping.diff.gz](https://github.com/inmanta/inmanta/files/3762343/resource-grouping.diff.gz)
