### ISSUE TITLE
Make -m option to inmanta module commit optional

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#2435]
**Problem:**

The `inmanta module commit` command has a mandatory `-m` option which indicates the Git commit message to use. Git itself would propose a commit message by opening an editor window when no commit message is given.

**Tasks:**

- [ ] Investigate whether it's possible to open an editor window with the commit message proposed by Git when `inmanta module commit` is used without the `-m` option.
- [ ] Implement the change when it turns out to be feasible.

**Comment by sanderr** [comment]
The command has been deprecated
