### ISSUE TITLE
support escaping of string interpolation open and close

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#2449]
As far as I know, the literal string `"{{x}}"` can not be constructed in the inmanta DSL without resorting to tricks such as
```
inner = "x"
whole = "{{{{inner}}}}"
```
I think it should be possible to escape the wrapping interpolation characters, though I'm not sure what exact syntax would be best suited.

**Comment by wouterdb** [comment]
partly adressed by https://github.com/inmanta/inmanta-core/pull/3502
