### ISSUE TITLE
Test failure on Fedora

### ISSUE THREAD

**Issue by andraskvr** [inmanta/inmanta-core#2551]
The test case test_data.py::test_get_latest_resource fails on fedora (tested via pytest-in-docker), with the latest core version.

[jenkins_log](https://app.zenhub.com/files/67439560/dfb1f6c8-fdb6-4814-a837-280c197e85a3/download)

I'm marking it unstable since it doesn't fail on other platforms, the error seems to be consistent on Fedora though

**Comment by bartv** [comment]
This was fixed. Closing it.
