### ISSUE TITLE
add pydantic support to Resource

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#2555]
I think it would be nice to support custom data classes using pydantic for resource field values. Since we now upload all module code to the agents, any type declared for a resource should be available for the agent as well to use in deserialization.'

# Steps to take
- design a way to specify a pydantic type for a field
- update `Resource.map_field` and `Resource.deserialize` to take this into account.

**Comment by wouterdb** [comment]
@sanderr give the inability of pydantic to handle polymorphism, is this still interesting?

I might be interesting to add a 'post-deserilaization' hook to the resources, this would allow any resource to be able to do custom de-serialization? 

(e.g. for Openstack, many resources refer to other resources. These references can have somewhat different forms. I have implemented a prototype on a branch there, where the references are polymorphic. After normal resource de-serialization, the references are converted from dicts into object by a custom de-serializer. A  'post-deserilaization' hook would help for this.

**Comment by sanderr** [comment]
Indeed, the original motivation for this was faulty, so I would be fine with closing this.

I do like your suggestion though if we can offer a clean API for it.
