### ISSUE TITLE
Deprecate the use of - in identifiers

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#2828]
We allow the use of - in identifiers but this creates problems and confusion:

- IDEs all see this is an operation so double clicking on the identifier does not work
- In python it is not supported and in plugins both names meet
- It will conflict with adding arithmetic to the language

Compiler deprecation framework already exists

Ensure we produce a warning of module names as well (in so far this is allowed currently)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/2828?planning-poker) with ZenHub @arnaudsjs @bartv @FloLey @sanderr
