### ISSUE TITLE
No handling of duplicated files (identical content, different path) in the uploading of the code to the server.

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta-core#2892]
If the code of a handler contains multiple times a file with the same content, for example, multiple `__init__.py` files at the root of different packages, only containing the copyright headers, the upload will fail with this kind of error:
```
Exception: Unable to upload handler plugin code to the server (msg: {'message': 'An unexpected error occurred in the server while processing the request: A file with this id already exists.'})
```

And somewhere in the logs we can see that indeed we try to upload twice a file with the same id.
```
INFO     tornado.access:web.py:2243 200 POST /api/v1/file (127.0.0.1) 1.11ms
INFO     tornado.access:web.py:2243 200 PUT /api/v1/file/2e8c1551b7a261141ff4144fd3908e5051f5ab64 (127.0.0.1) 1.16ms
INFO     tornado.access:web.py:2243 200 PUT /api/v1/file/e2c256c7be1324c9b5335972a147d68e2ede897b (127.0.0.1) 1.04ms
INFO     tornado.access:web.py:2243 200 PUT /api/v1/file/208920ec7ffacd098532bd6abc8316c89c9a7231 (127.0.0.1) 0.74ms
ERROR    tornado.access:web.py:2243 500 PUT /api/v1/file/e2c256c7be1324c9b5335972a147d68e2ede897b (127.0.0.1) 1.28ms
```

This comes from the fact that files are identified only by a hash of their content during this upload process.
https://github.com/inmanta/inmanta-core/blob/5bfe60683f7e21657794eaf222f43e4c53540bb5/src/inmanta/loader.py#L61-L69

The upload is happening here: 
https://github.com/inmanta/inmanta-core/blob/5bfe60683f7e21657794eaf222f43e4c53540bb5/src/inmanta/export.py#L81-L99

**Comment by sanderr** [comment]
This is a duplicate of #2313 I think.

**Comment by edvgui** [comment]
Indeed, I will close this one.
