### ISSUE TITLE
Importing the ABCs from 'collections' is deprecated

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#2977]
The following deprecation warning shows up on `python3.8`:

```
/opt/inmanta/lib64/python3.8/site-packages/inmanta/execute/proxy.py:19: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
```

**Comment by tirkarthi** [comment]
Fixed in https://github.com/inmanta/inmanta-core/commit/f6632fecba2699bf4c68b4e54ac40e5085ccb15d

**Comment by sanderr** [comment]
@arnaudsjs did you get this issue for iso3? It does seem to be fixed for iso4+ and I don't think we need python3.8 support for iso3.

**Comment by arnaudsjs** [comment]
I don't remember exactly.
