### ISSUE TITLE
Protected environment raises 403

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#2991]
When an environment is set as protected, the orchestrator raises a 403 on the 3 protected operations.

The 403 will trigger the dashboard to issue an error concerning authentication. We should keep 403 for forbidden because of authentication and use another error code for protected.

For example `409 Conflict` could be an option?

**Comment by FloLey** [comment]
closed after discussion [here](https://inmanta.slack.com/archives/C045Y42N49W/p1704809268537349) and [here](https://inmanta.slack.com/archives/CKRF0C8R3/p1704809001782969)
