### ISSUE TITLE
Remove processing_events resourcestate from database schema

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#3024]
The `processing_events` state has been deprecated in #3020, but the database type `resourcestate` still contains the `processing_events` element in order to be able to see the `processing_events` deployment action for passed deployments. This issue should remove the `processing_events` item from the `resourcestate` enum in the database schema.

**Comment by FloLey** [comment]
done here: https://github.com/inmanta/inmanta-core/blob/17484701e1bf85722a59881444d4669907052749/src/inmanta/db/versions/v202209130.py
