### ISSUE TITLE
improve compiler determinism

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#3034]
Part of the compiler is non-deterministic. `QueueScheduler` uses a set for `all_statements`. This should be made to behave deterministically, ideally by introducing a data structure with `O(1)` add and remove which has a conclusive ordering.
(or stabilize the hash)

See #3026.

Example of non-deterministic snippet:
```
entity A:
end

A.list [0:] -- A
A.optional [0:1] -- A

implementation a for A:
    self.optional = A()
end

implement A using std::none
implement A using a when std::count(self.list) > 0

a = A(list=A())
test = a.optional
```

__________________________________________
Florent 16/02:

I tried to change the `all_statements: Set[Waiter]` by `all_statements: List[Waiter]` and changing what was needed to make it work but it did not fix the non-deterministic behavior.
However I think I found the line where the behaviors start to diverge:

https://github.com/inmanta/inmanta-core/blob/0315526a6f9f3caf25540ab83a0fe1320f137cff/src/inmanta/execute/scheduler.py#L345

The `waitqueue.popleft()` seems to not always pop the same object when reaching this part of the code for the first time (with the exemple snippet)

- Sometimes it pops: 
`ListVariable __config__::A (instantiated at ./main.cf:14) __config__::A.list = [__config__::A 7fe174458af0]`
and then it succeeds to compile. 

- Sometimes it pops:
`OptionVariable __config__::A (instantiated at ./main.cf:14) __config__::A.optional = None`
and the it fails

As waitqueue is a `Deque` I suppose elements are not always added in the same order to it but I don't understand the
`QueueScheduler` enough right now to investigate this further.

**Comment by wouterdb** [comment]
It might be worth investigating how performance is if we use a normal list?

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3034?planning-poker) with ZenHub @arnaudsjs @bartv @FloLey @sanderr
