### ISSUE TITLE
Modules V2 - Research - poetry

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#3037]
- Verify that poetry does perform something equivalent to `pip -e` 
- Determined a convenient way find where the '.cf' files are located, given the python part is installed by poetry
- Verify this works with namespace packages

**Comment by sanderr** [comment]
@arnaudsjs you might have already figured this out but I just stumbled upon `pkg_resources.resource_filename`, which could be an answer to the second bullet.

**Comment by arnaudsjs** [comment]
1) Does poetry perform a `pip install -e` on the project by default?
    * Yes it does.
2) Determine a convenient way to determine where the *.cf files are located.
    * On Python 3.6: The `pkg_resources` library can be used to browse the directories and open files of an installed python package. This library works for editable and normal installs of a python package.
    * On Python 3.7+: The `importlib.resources` should be used instead of the `pkg_resources` library. This library provides the same feature set as `pkg_resources`.
3) Verify this works with namespace packages
    * Poetry works with namespace packages. Namespace packages can be created as defined in the design document.

Example: usage `pkg_resources` library:
```
>>> import pkg_resources
>>> pkg_resources.resource_listdir("inmanta_plugins.mod1", "files")
['additional_file.txt', 'test']
>>> file_path = resource_filename("inmanta_plugins.mod1", "files/additional_file.txt")
>>> print(file_path)
/home/arnaud/Documents/tmp/modules_v2/test-project/venv/lib64/python3.6/site-packages/inmanta_plugins/mod1/files/additional_file.txt
>>> with open(file_path, "r", encoding="utf-8") as f:
...   print(f.read())
file content
```

Example: usage `pkg_resources` library:

```
>>> import importlib.resources
>>> import os
>>> with importlib.resources.path("inmanta_plugins.mod1", "files") as f:
...    print(f)
...    os.listdir(f)
... 
/home/arnaud/Documents/tmp/modules_v2/test-project/venv/lib64/python3.8/site-packages/inmanta_plugins/mod1/files/additional_file.txt
['additional_file.txt', 'test']
>>> with importlib.resources.path("inmanta_ext.mod1", ".") as p:
...    with open(os.path.join(p, "files/additional_file.txt"), "r") as f:
...       f.read()
... 
file content
```
