### ISSUE TITLE
Modules V2 - Research - poetry plugins

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#3038]
Investigate what extensions capabilities poetry offers 

starting point: https://github.com/python-poetry/poetry/issues/693 

timesbox: 1day

**Comment by sanderr** [comment]
Conclusions:
- poetry has support for plugins but currently only on master, not yet on any released version
- 2 plugin types: `Plugin` gets activated when poetry starts, `ApplicationPlugin` can register additional commands and options. The latter would be most suitable for our use cases.
- fairly little documentation. The basics of how to register a plugin are there, but there is no documented core poetry interface. If we'd want to hook into the core poetry code, we'd need to look at the source. `poetry.masonry.builders` might be a place of interest.
