### ISSUE TITLE
update vscode to work with the new modules workflow

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#3080]
Currently vscode installs itself in the compiler venv. 

With modules v2, a compiler venv should no longer be required. The vscode extension should instead ask to install in the selected Python environment.

Verify if compiler warnings are passed on to the user. If not, make a ticket and add it as blocking the vscode release.

**Comment by wouterdb** [comment]
make sure to do a release for the fix introduced here: https://github.com/inmanta/vscode-inmanta/pull/279

**Comment by sanderr** [comment]
I've created a separate ticket for the vscode release: inmanta/irt#914
