### ISSUE TITLE
Modules V2 - inmanta module add

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#3089]
Add a command to install a new dependency and add it to either the project or the module or both as meta-data. 

If the current path (cwd) contains both a module and a project, prompt the user where to put the dependency

**Comment by arnaudsjs** [comment]
@wouterdb @sanderr I think it makes sense to add an `-I` option to the `inmanta modules add` command that also triggers an install after adding the module to the metadata. This should be a very common use case. Any objections? Suggestions?

**Comment by wouterdb** [comment]
I think with poetry the default is to always install on add

**Comment by wouterdb** [comment]
npm used to have `npm add --save` and `npm install` but now apparently,  both add and install are the same thing (they both do both) https://stackoverflow.com/questions/51466746/difference-between-npm-add-and-npm-install-save

**Comment by wouterdb** [comment]
so perhaps we also have to do both by default?

**Comment by arnaudsjs** [comment]
> I think with poetry the default is to always install on add

I was also thinking about that possibility. Makes sense to me. Then we can add a `--no-install` option, but maybe we don't even need that option. I can't think of a use case where it would be required.
