### ISSUE TITLE
Document modules V2 capabilities for the agent

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#3090]
# Problem

- Modules V2 offers extended capabilities (such as packaging additional helper classes in other folders). 
- The agent upload mechanism doesn't necessarily support all of these.

# Goal

- [ ] Determine which capabilities current work and which limitation are there.
- [ ] Summarize and report to the team to determine how we will handle all cases. 

# Attention points

- Additional python files in other folders
- requirements in setup.cfg instead of requirements.txt 

# Partial evaluation of current (intermediate) behavior based on #3083 
- v2 modules' code is put in the `Code` table just like v1 modules
- `Code.requires` does not include requirements on `inmanta-module-*`
- Cross-module dependencies only work if both modules happen to be loaded on the same agents
- editable installs work as expected

# Long term considerations
- having the server expose a pip index where it publishes its v2 modules and inherits from another index for all other requirements might be an approach worth consideration.

**Comment by sanderr** [comment]
Report:
- The ticket mentions modules v2 offers the capability to package additional helper classes in other folders, but this is not necessarily a modules v2 thing but more an agent code loading thing, isn't it? I think this is currently supported for both v1 and v2, though somewhat unstable (#3310).
- As a general rule, on the agent, v2 modules behave mostly the same as v1 modules: source code is collected and loaded on the agent. Inter-module dependencies are not guaranteed to work on the agent. The fact that you're using a v2 module, or whether it's an editable install, is currently transparent to the agent.

Concluding: modules v2 currently doesn't really offer any benefits on the agent side. It does offer potential though. Inter-module dependencies can now be easily declared in the form of Python dependencies (though #3310 is probably a blocker for actual stable support). So I believe the next step would be to improve code serving from the server to the agents (some brainstorming was already done on this and some proposals were made (the ticket description mentions one), but nothing really concrete). This should unlock all modules v2 potential for the agent, and conversely I don't really think we can take any intermediate steps to unlock this potential.

**Comment by sanderr** [comment]
Created #3523 as follow-up
