### ISSUE TITLE
update cookiecutter template for modules v2

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#3100]
stage on a branch, don't put on master until this is ready for prime-time

- make sure project and module include the std dependency by default (https://github.com/inmanta/inmanta-core/pull/3258#discussion_r709010897)
- make sure template contains `MANIFEST.in` instead of the `options.package_data` section in `setup.cfg`

**Comment by arnaudsjs** [comment]
The branch `issue/3100-create-v2-modules` was created on the `inmanta-module-template` repository. However, the tests do not succeed since pytest-inmanta is incompatible with v2 modules. I will add the dependency on pytest-inmanta to this ticket.
