### ISSUE TITLE
__cfcache__ directories not deleted from venv

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#3183]
When a V2 module is installed (non-editable install) and the compiler runs against it, a `__cfcache__` a directory is created in the model directory of the installed package. When the module is later on deleted from the venv, the `__cfcache__` directory is not deleted from the venv.

```
 ~/.virtualenvs/inmanta-core/lib/python3.6/site-packages/inmanta_plugins/elaboratev2module $ find .
.
./model
./model/__cfcache__
./model/__cfcache__/_init.2020_6.cfc
````

**Comment by sanderr** [comment]
Duplicate created in #4360. Closing this one because the duplicate covers breaking implications in addition to the behavior observed here.
