### ISSUE TITLE
Queries can not be used without assigning their value

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta-core#3367]
It seems that using a query without assigning it to a variable raises a `ParserException`, though I would have expected this to be semantically correct.

The model below will raise a parsing error on the last line:
```
import test

test::Test(
    testt="a",
    tests=test::Test(testt="b"),
)

# This is valid
a = test::Test[testt="a"]

# This is not
test::Test[testt="a"]
```
```
inmanta.parser.ParserException: Syntax error at token [ (./main.cf:10:12)
```

Here is a project which allows to reproduce the error: [model.zip](https://github.com/inmanta/inmanta-core/files/7388926/model.zip)

**Comment by wouterdb** [comment]
Expression should be treated as statements

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3367?planning-poker) with ZenHub @arnaudsjs @bartv @FloLey @Hugo-Inmanta @sanderr
