### ISSUE TITLE
Make web-console the default UI

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#3496]
The goal of this EPIC is to make the web-console the default view for everyone, including OSS.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3496?planning-poker) with ZenHub @sanderr @arnaudsjs @FloLey @bartv
