### ISSUE TITLE
E2E test on modules V2

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#3533]
# Things to do first

-> push std to pypi 

# Who

florent (new)
guillaume (experienced)
pouriya (medium)

# What

- quickstart
- cookiecutter V2 met pytest 
  - add test for a std::len
- convert a v1 to v2 (guillaume)

# instructions

1. [quickstart](https://docs.inmanta.com/community/dev/quickstart.html)
2. [developer getting started](https://docs.inmanta.com/community/dev/model_developers/developer_getting_started.html)

**Comment by sanderr** [comment]
Additional task for @edvgui (not yet, I'll ping you):
6. Add a new v1 module using the cookiecutter template and import it from the project -> compile. Then convert it to a v2 module and make sure the project still compiles.
