### ISSUE TITLE
Check build failure of iso4 fedora-latest 

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#3536]
# Observed behavior
https://jenkins.inmanta.com/job/integration-tests/job/pytest/1743/branch=iso4,os=fedora-latest/console

```
______________________________ test_basic_install ______________________________

tmpdir = local('/tmp/pytest-of-user/pytest-0/test_basic_install0')

    def test_basic_install(tmpdir):
        """If this test fails, try running "pip uninstall lorem dummy-yummy iplib" before running it."""
        env_dir1 = tmpdir.mkdir("env1").strpath
    
        with pytest.raises(ImportError):
            import lorem  # NOQA
    
        venv1 = env.VirtualEnv(env_dir1)
    
        venv1.use_virtual_env()
        venv1._install(["lorem"])
>       import lorem  # NOQA
E       ModuleNotFoundError: No module named 'lorem'

home/user/code/tests/test_env.py:42: ModuleNotFoundError

```

# Cause
After initial investigation the cause seems to be that `inmanta.env.VirtualEnv` does not take multi-digit minors for Python versions into account: https://github.com/inmanta/inmanta-core/blob/4f019055bff5b1dd33f865293cb61465a2c5ab66/src/inmanta/env.py#L140. This has been fixed on master already: https://github.com/inmanta/inmanta-core/blob/76ef7f2a5ff43d46bfb8e8ad647eb550f7cb57d8/src/inmanta/env.py#L216. The fix should be applied on iso4.

**Comment by sanderr** [comment]
Fedora latest seems to have python3.10 as the default. Managed to reproduce this on my machine with python3.10.
