### ISSUE TITLE
editable module install requires recent pip

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#3552]
`inmanta module install -e .` is broken on pip version 20.0.2 because it does not support editable installs for projects without a `setup.py`. Investigate which version of pip is required for this to work and either add a constraint to core's `setup.py` or mention this constraint in the docs. The former is probably the safest option but opinions might differ: communicate with the team.

- [x] add constraint to setup.py to be larger '21.3'
- [x] verify this works (install inmanta-core on old pip)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3552?planning-poker) with ZenHub @sanderr @arnaudsjs @FloLey @bartv
