### ISSUE TITLE
drop intercomponent version constraints for stable components

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#3624]
# Tasks
Update designs and release docs to drop development line constraints from `inmanta-license`, `inmanta-support` and `inmanta-ui`. We leave the current constraints in place in order to err on the side of caution with regards to actual compatibility, but in the future the constraints should not be updated unless required for compatibility.
- [x] Update the iso3-4-5 design document to state that for these three repos no internal constraints should be set to constrain it to the product line, only to constrain for compatibility. Also add the reasoning and make clear that this differs between these repos and the other components.
- [x] Update the tasks for the major release to no longer update the internal constraints for these repos.

# Motivation
The packages listed above are **very stable (rarely change) and generally don't depend on a specific version of any of the other extensions**. Yet in the current iso3-4-5 design, they constrain each other and/or `inmanta-core` to the same iso development line. As a result they receive a major version bump each year, while the code has hardly, if at all, changed.

Since the product package already constrains everything to the product line, and no modules or other packages depend on these packages, it should suffice to only constrain based on compatibility rather than on the development line.

# Original ticket description
Both products constrain their components in their `setup.py` and `pyproject.toml` to the relevant range (`>=x.y.z.dev`/`~=x.y.dev`/`~=x.y.z.dev`). Similarly, components that depend on other components constrain them in their `setup.py`. This has the following consequences:
- greatly complicates the major release process: requires updating constraints on all repos that have internal dependencies on all 3 branches
- for some repos this is the sole reason a new major iso leads to branch divergence and a version bump, often resulting in multiple identical versions, apart from the version number, which is not according the the SemVer convention.
- when two branches for a repo (for example `inmanta-core`) do diverge at some later point, full correctness would require bumping the constraints on the master branches of all products and components that depend on it.

Now, what benefits do these constraints offer us? As far as I recall the only reason for these constraints is for CI/CD.

With all these complications and CI/CD consistency the only goal, might there be an alternative solution? Perhaps we could centralize these constraints somehow? Perhaps a product set (`iso4`, `iso5`, `master`) constraints file similar to the module sets we have? This could then be used as constraints file for all test pipelines, both on a product level and an individual component level.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3624?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
