### ISSUE TITLE
Clear environment does not call listeners when rmtree fails

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#3637]
environment_clear does not call listeners when rmtree fails. This commonly fails when someone manually as the root user did a git pull on a module.

make sure listeners failure doesn't cause the next one to fail (should have try/expect)

When the environment is deleted in core, it should first call all listeners before it tries to delete the code tree.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3637?planning-poker) with ZenHub @sanderr @arnaudsjs @FloLey @bartv
