### ISSUE TITLE
update core documentation to refer to web console instead of dashboard

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#3648]
- [x] `grep dashboard --include "*.rst" -R docs/` -> update relevant occurrences
- [x] update dedicated dashboard page to state it has been deprecated and replaced by web console. Refer to `extensions/inmanta-ui`.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3648?planning-poker) with ZenHub @sanderr @arnaudsjs @FloLey @bartv
