### ISSUE TITLE
Remove Centos8 installation documentation because it's end-of-life

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#3660]
The installation documentation refers to Centos8, while it's end-of-life. Should we refer to Rocky Linux instead?

**Comment by bartv** [comment]
I would make it refer to rhel and then mention that any of the community
editions will work as well

**Comment by arnaudsjs** [comment]
This issue was already resolved in #3748 and inmanta/inmanta-service-orchestrator#247
