### ISSUE TITLE
Create endpoint to fetch dryrun / compare from the server

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#3668]
The goal of this ticket is to create an API endpoint that uses the current dry-run data to create a decent diff that can be show in the web-console. In later tickets the server-agent API will be improved to allow handler to provide more details diff information.

For each dryrun the database will hold a list of resources. For each attributes a dict is kept with current and desired state. The API should return a similar summary:

1. High level dryrun information
```json
{
        "id": "b38ee08c-5d30-499f-bc26-aceabf4309fe",
        "environment": "f81be80b-8582-499f-b002-7cdd2f2df98a",
        "model": 1572537088,
        "date": "2022-01-27T18:46:35.427130",
        "total": 3493,
        "todo": 3006,
}
```

2. The actual dryrun / compare data. The goal is to return a similar structure like for the desired state compare. With the stored current and desired attributes in their stored form and then also a current_compare and desired_compare which is a string.

In the current API the parsed ID field is returned, but this has not added value for the new api.

The requires field should never be included because this makes no sense for a dryrun.

Note: The endpoint must not use the hashes and parsed fields so that at a later point in time we can start changing how the data is stored in the database.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3668?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
