### ISSUE TITLE
OSS installation docs fixes for iso5

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#3721]
- don't mention CentOS 7
- expand instructions for non RHEL based distros to install and enable inmanta-ui + web-console
- fix the distro tabs (see stable OSS docs)

**Comment by arnaudsjs** [comment]
Install instruction for PostgreSQL 13 are already there

**Comment by sanderr** [comment]
Indeed, apparently I was looking at the stable OSS docs. For the dev docs it looks like the tabs for the distributions don't work though (they are just listed one below the other). I'll add that instead.
