### ISSUE TITLE
Create v2 endpoint to request a new dryrun

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#3723]
The goal of this ticket is to create a v2 call for requesting a dryrun. Based on the current requirements the v1 and v2 method should be equivalent.

It should only return the ID of the dryrun.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3723?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
