### ISSUE TITLE
Create an v2 endpoint to list all dry run reports

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#3724]
Create a method similar to the current v2 method but with correct  return type typing.

It is important that this list is sorted on the date the dryrun was requested.

The version should not be optional.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3724?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
