### ISSUE TITLE
Unclear error when compiler venv has incompatible Python version

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#3829]
The compiler currently expects the compiler venv to have the same Python version as the active process. I think this is a valid expectation. When this is violated however it does not give a clear error message. Instead a hard to diagnose `FileNotFound` error is raised.

Steps to reproduce (from a 3.9 environment with `inmanta-core>=6` installed):
```console
(inmanta-core-39) sander@bedevere:~/downloads/venvtest$ python3.6 -m venv .env
(inmanta-core-39) sander@bedevere:~/downloads/venvtest$ python -c 'from inmanta.env import VirtualEnv; VirtualEnv(".env").init_env()'
CREATING
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/env.py", line 702, in init_env
    self._write_pth_file()
  File "/home/sander/documents/projects/inmanta/inmanta-core/src/inmanta/env.py", line 765, in _write_pth_file
    with open(self._path_pth_file, "w", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '.env/lib/python3.9/site-packages/inmanta-inherit-from-parent-venv.pth'
```

I believe a guard should be put in place: the `init_env` code should check if `self.site_packages_dir` exists. If it doesn't, this means the venv hosts a different Python version than the running process, in which case an exception should be raised.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3829?planning-poker) with ZenHub @arnaudsjs @bartv @FloLey @Hugo-Inmanta @sanderr

**Comment by rohitsharma11607471** [comment]
Hi @wouterdb I am starting out as contribute and would help to contribute. Would you help me with how should i start?
