### ISSUE TITLE
Add support to add a not to the resource state in the v2 resource list

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#3845]
Currently only inclusive filters can be used. However, to hide orphans by default it makes a lot more sense to use "!orphans'

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3845?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
