### ISSUE TITLE
Update classifiers in setup.py

### ISSUE THREAD

**Issue by andraskvr** [inmanta/inmanta-core#3851]
The classifiers in setup.py still list python 3.5 on master, while 3.8 and 3.9 are not mentioned at all:
https://github.com/inmanta/inmanta-core/blob/b364df85f4e90b5fde983c1721f02205e7090edb/setup.py#L65

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3851?planning-poker) with ZenHub @arnaudsjs @bartv @FloLey @Hugo-Inmanta @sanderr
