### ISSUE TITLE
Improve compiler error message

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#3902]
When an attribute or relation that is part of the constructor the following message is given for example:

```
attributes police are part of an index and should be set in the constructor. (reported in Construct(pm::Rate) /module/model/mpls/ciscoxr.cf:77))
```

However this message could be improved by doing the following:
1. In this case it is a relation but the message says attributes.
2. It only implicitly mentions the type
3. The import rewrites the name so it does not point directly to the type or the index

A potential improved message could be:

**Invalid Constructor call: missing relation 'police'. The relation ciscoxr_services::policy_map::Rate.police is part of an index.**

For an attribute it should say **attribute**

**Comment by wouterdb** [comment]
or perhaps even 

```
Invalid Constructor call: missing attribute 'police'. The attribute ciscoxr_services::policy_map::Rate.police is part of an index.
```

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3902?planning-poker) with ZenHub @arnaudsjs @bartv @FloLey @Hugo-Inmanta @sanderr
