### ISSUE TITLE
lsm::LifecycleTransfer.resources list should be sorted

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#3904]
The resources list does not diff very well because the lists are not sorted.

![image.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/49b89ee2-c9c9-434b-bf64-fec6abfcff0d)

Eventually it would be good if the handlers could provide a compare version to the server (or more type information). Until then the server should handle some fields a bit special (like with requires).

The goal of this ticket is to introduce a method or module that groups all of these and add a first one that sorts the resources attribute of the lsm lifecycle resource.

**Comment by wouterdb** [comment]
moved to lsm
