### ISSUE TITLE
Attach a warning to the current state compare when agents are not started.

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#3905]
When a dryrun is requested, it will only get results for resource of which the agent is actually running. The goal of this ticket is to perform a check if there are any that are not started. If that is the case, the list of agents should be added to the dry run record in the database.

When a dryrun is fetched, the diff status of these resource should be set to 'no agent' and be included in the total count.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3905?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
