### ISSUE TITLE
Inmanta deploy command fails when the database config options are set to non-default values

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#3927]
**Problem description:**

The `inmanta deploy` command sets up a PostgreSQL server and an Inmanta server to deploy a model. The PostgreSQL server set up by this command expects the Inmanta server to connect to it with the `database.username` config option set to `postgres`. This is the default value for that option. The `inmanta deploy` command fails when any of the inmanta configuration files sets the `database.username` config option to a different value then `postgres`. The same issue exists for the `database.host` config option.

**Solution:**

Force the above-mentioned config options to a specific value in https://github.com/inmanta/inmanta-core/blob/728fe7de6894dabc7c5a218cb1cb6c91b80ecc8f/src/inmanta/deploy.py#L100

timebox to 2 h
**Workaround:**

Add a `.inmanta` file with the following content to the directory where the `inmanta deploy` command is executed:

```
[database]
host=localhost
username=postgres
```

**Additional notes:**

It has to be investigated whether a similar issue exists for other configuration options.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3927?planning-poker) with ZenHub @arnaudsjs @bartv @FloLey @Hugo-Inmanta @sanderr
