### ISSUE TITLE
Add notification cleanup

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#3982]
The goal of this ticket is to create a background task that regularly cleans notifications from the database.

- [ ] Add an environment settings for the amount of days to keep notifications. By default set it to 365 days
- [ ] Add a cleanup task to the delete all messages that are older than the number in the settings. Run the task every hour and run it at startup. The task has to fetch the new config every time.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3982?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
