### ISSUE TITLE
Compiler performance has decreased

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#4055]
The runtime of the tests of the lsm module has increased. After investigation it turned out that the `project.compile()` method of the `project` fixture of `pytest-inmanta` project, has become substantially slower. The assumption is that this performance degradation is related to the introduction of module V2.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/4055?planning-poker) with ZenHub @andraskvr @arnaudsjs @FloLey @Hugo-Inmanta @sanderr @bartv

**Comment by wouterdb** [comment]
if the fix takes over 1 day, make it into a ticket

**Comment by arnaudsjs** [comment]
The profiling information showed that the slowdown of the tests is mainly caused by spawning the `pip` sub-process to install module dependencies. `pip` is invoked approximately two times for each test case that uses the `project` fixture:

* Once in the setup stage of the `project` fixture of pytest-inmanta.
* Once when the test case invokes `project.compile()` on that fixture.

The implementation prior to modules V2, installed module dependencies only when the plugin loading failed. This saved a lot of expensive calls to `pip`. The new implementation always invokes `pip`, due to the nature of modules V2.
