### ISSUE TITLE
PythonEnvironment assumes venv

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#4091]
The implemementation of `inmanta.env.PythonEnvironment` assumes it's running in a virtual environment. The location of the site-packages dir in particular is venv-specific and wouldn't be compatible with a system Python. Attempting to run inmanta like `/usr/bin/python -m inmanta.app` would add `/usr/site-packages` to the sites dir. This likely breaks `inmanta project install` in this scenario, and might have a whole range of other undefined behaviors.

1. Figure out the impact (what is affected)
2. Figure out if we can work around 
3. requeue or make a new ticket

**Comment by sanderr** [comment]
Looking at this ticket again now I'm wondering if this is just a reasoning error. As far as I can see right now the structure of the python binaries and site packages for system Python is actually very similar to the venv ones (the example above does not seem correct). I assume it's even more the other way around that `venv` models the system structure. I think we can just close this one.

**Comment by arnaudsjs** [comment]
Is it a problem that the `bin` directory of the venv is in a different location?

**Comment by arnaudsjs** [comment]
I think you are right.

**Comment by arnaudsjs** [comment]
It was verified that the above-mentioned use case works fine with the current implementation.
