### ISSUE TITLE
Perform input validation on provided resource sets

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#4328]
Verify that each resource_id provided in the `resource_sets` argument of the `put_version()` API endpoint matches a resource_id in the `resources` argument.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/4328?planning-poker) with ZenHub @andraskvr @arnaudsjs @FloLey @Hugo-Inmanta
