### ISSUE TITLE
Improve logging in VirtualEnv class

### ISSUE THREAD

**Issue by andraskvr** [inmanta/inmanta-core#4343]
The `__init__` method of the VirtualEnv class logs that a new virtual environment is being created:
https://github.com/inmanta/inmanta-core/blob/d6e5d1d25320fd15dc1ff2fdbf30474eae3f83ff/src/inmanta/env.py#L717

That's misleading, because if the path already points to a virtual env, it will not be recreated, simply used.
(When a new environment is actually created on disk, it's logged differently, on debug level: https://github.com/inmanta/inmanta-core/blob/d6e5d1d25320fd15dc1ff2fdbf30474eae3f83ff/src/inmanta/env.py#L773)

I would propose removing the `creating...` log line from the `__init__` method, and adding a line with `initializing...` or `using...` to the `init_env` method: https://github.com/inmanta/inmanta-core/blob/d6e5d1d25320fd15dc1ff2fdbf30474eae3f83ff/src/inmanta/env.py#L731

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/4343?planning-poker) with ZenHub @andraskvr @arnaudsjs @FloLey @Hugo-Inmanta
