### ISSUE TITLE
V2 modules not fully uninstalled by `pip uninstall`

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#4360]
# Description
The compiler now has AST caching enabled by default. For v2 modules (not in editable mode) these cache files are saved in a `__cfcache__` directory next to the corresponding model files. However, since these files are not included in the Python build artifacts (nor should they be), they apparently are not considered owned by the package. As a result they are not deleted by `pip uninstall`. This results in a broken compiler state because the namespace package `inmanta_plugins.themodule` still exists but it is now empty -> the compiler tries to load the v2 module but fails in an unexpected way.

# Steps to reproduce
```sh
mktmpvenv
pip install inmanta-core --pre
pip install inmanta-module-std
inmanta compile
pip uninstall inmanta-module-std # shows "would not remove: ...__cfcache__..."
inmanta compile # fails
ls "$(cdsitepackages && pwd)/inmanta_plugins/std/model/__cfcache__/" # exists
```

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/4360?planning-poker) with ZenHub @andraskvr @arnaudsjs @FloLey @Hugo-Inmanta

**Comment by arnaudsjs** [comment]
Issues #4407 and #4408 were created to resolve this issue.
