### ISSUE TITLE
The set_setting endpoint return status code 500 on invalid value

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#4361]
The `set_setting` API endpoint returns a status code 500 when an invalid value is provided. This should be status code 400.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/4361?planning-poker) with ZenHub @andraskvr @arnaudsjs @FloLey @Hugo-Inmanta
