### ISSUE TITLE
Add inmanta-workon command to the rpm

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#4376]
# Problem

One of the common steps when diagnosing issues with production orchestrators is to manipulate the module and venv on the server directly via the cli

This is currently a bit involved because
- the folder is deeply nested `/var/lib/inmanta/server/environments/`
- venv needs to be activated
- even when the venv is activated, the inmanta command doesn't work (for iso 5) (see #4259)
-  the environment can not be adressed by name

This also often leads to problem when the root user is used in the folder, making it impossible for the inmanta user to modify them

# Solution

Provide an inmanta-workon command in the rpm that 
- changes the working dir to the project dir
- activates the venv
- registers a inmanta-deactivate alias that, when called, verfies if there are files in the working dir that are not owned by inmanta. If this is the case, a warning is produced. 
- syntax: `inmanta-workon <environment_name>|<environment_id>`, raise an exception if env is not unique + list all environments with uuids.
- if authentication is enabled, need to use uuid
- update RPM specfiles to put the executable in `/usr/bin/`
- make sure `inmanta` command works and operates on the activated environment

**Comment by sanderr** [comment]
Done
