### ISSUE TITLE
regular timeouts on core tests

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#4384]
The core tests and Pytest in Docker regularly timeout (Jenkins timeout, not python timeout) on `tests/server/test_server_status.py`. This seems to happen every few days (both on slow and fast runs). So far we've been unable to reproduce it consistently. This ticket is meant to keep track of what has been tried to investigate this, as well as collect helper scripts for future investigation.

# Reliable reproduction (sort of)
Based on the "Preceding tests" section below I managed to set up a Jenkins job for a reliable reproduction. It executes pytest 300 times on four tests in a given order. This takes about 45 minutes if successful. However, luckily most runs aren't successful and the timeout occurs somewhere down the road. The Jenkins job can be found [here](https://jenkins.inmanta.com/job/core/job/inmanta-core/job/timeout-experiments-2/). I didn't change anything on Jenkins' side, only modified tox a bit on the `timeout-experiments-2` branch.

I have not yet investigated whether the run of four tests used here are actually a minimal set to reproduce this (I expect not). Feel free to experiment as you like with the branch. At the time of writing the tox command config used is the following:
```
commands=sh -c 'seq 300 | xargs -I_i_ sh -c "echo run _i_ && py.test --log-level DEBUG --junitxml=junit-{envname}.xml -vvv {env:INMANTA_EXTRA_PYTEST_ARGS:} --randomly-dont-reorganize tests/agent_server/test_evolution.py::test_resource_evolution tests/server/test_server_status.py::test_server_status_database_unreachable tests/server/test_server_status.py::test_server_status tests/compiler/test_is_defined.py::test_is_defined_block_scoping[if\ in\ implementation\ self]"'
```

# First occurrence
This issue was first observed in Pytest in Docker build 1905 on 2022-06-07. The build logs at the time of writing only go back until 2022-05-23. Within that window no other instances of this issue were found. Given the infrequency with which this occurs, nothing can be said with certainty about when exactly the root cause was introduced, but it seems likely (because of the large amount of tests run in Pytest in Docker every day) that it was on or a few days before 2022-06-07.

# Preceding tests
A potential cause could be that one or more of the preceding tests occasionalmultiple timesly result in a state where the timeout occurs. If this is indeed the case, we might be able to pinpoint which tests are responsible by collecting data from each build that timed out this way.

Below is an overview of all relevant builds so far:
- [936.txt](https://app.zenhub.com/files/67439560/630bcc78-b31e-4dd4-9274-e6dd99eb4b57/download)
- [943.txt](https://app.zenhub.com/files/67439560/c4efba45-4bfc-48b1-b1fc-c3ddebc41401/download)
- [docker-1905-master-fedora-latest.txt](https://app.zenhub.com/files/67439560/afe9fef9-ed8b-4314-861e-86265f7d6308/download)
- [docker-1907-iso5-stable-fedora-latest.txt](https://app.zenhub.com/files/67439560/c33b96c2-012e-4433-9e94-996d840d2dca/download)
- [docker-1911-master-centos8.txt](https://app.zenhub.com/files/67439560/c0a6221e-c5f3-401b-8665-0c30a6e08770/download)
- [docker-1912-iso5-ubuntu-rolling.txt](https://app.zenhub.com/files/67439560/e23c680b-a860-45c3-9fab-c38493bc7e02/download)

The files list all (non-skipped) tests up to the timed out one, in the order in which they were run. From this the tests that occurred in all runs can be determined: [all-6.txt](https://app.zenhub.com/files/67439560/85f7fd48-8cf5-472e-bcd2-e947b7df547d/download) (number in the name indicates number of builds included when file was generated). These can then be run with `xargs -a <file> pytest --randomly-dont-reorganize`. So far I did not manage to reproduce the issue using this approach (about 200 runs at the time of writing, part on my local machine, part on Jenkins).

The single build files above were obtained using the following procedure:
- copy all test lines from Jenkins output
- `grep -v " SKIPPED " <input> | sed 's/^\(..:..:.. \)\?\(.*\) \(PASSED\|FAILED\) .*/\2/'  > <output>`

The common tests were then determined with `grep -Ff <one> <two> | grep -Ff <three> | ...`.

# Randomly seed
Attempts were made to run with the same randomly-seed on the same commit as one of the timed out builds. So far (10+ builds at the time of writing) this did not manage to reproduce the issue.

# Jenkins agent
Both builds so far ran on jenkins runner 2. This runner does not result in consistent timeouts, even when combined with the randomly seed approach (at the time of writing only forced one such build on jenkins runner 2).

# Stack dump
This has not been tried yet but is the next path to be explored. If we could temporarily set up the Pytest in Docker and/or core test jobs to detect timeouts like this and export a dump, this could give some more information as soon as the issue pops up again.

**Comment by arnaudsjs** [comment]
This issue is caused by a deadlock in the database locking mechanism. What happens is the following:

1. When the server stops, the Scheduler [cancels all tasks that are in flight]( https://github.com/inmanta/inmanta-core/blob/630982b62795c784dd52293da3e0d4b3c5799309/src/inmanta/util.py#L331). This includes tasks that access the database like the job that [cleans up the old Compile reports](https://github.com/inmanta/inmanta-core/blob/630982b62795c784dd52293da3e0d4b3c5799309/src/inmanta/server/services/compilerservice.py#L512). Each of these queries implicitly acquire a lock on the records they access. These locks are normally automatically released when the query finishes execution.
2. Due to a bug in the asyncpg library, these lock are not freed correctly when an in flight query gets cancelled.
3. As such, the cleanup [clean_db](https://github.com/inmanta/inmanta-core/blob/630982b62795c784dd52293da3e0d4b3c5799309/tests/conftest.py#L400) fixture, that executes a TRUNCATE query, hangs because [these types of query require an exclusive lock](https://www.postgresql.org/docs/current/sql-truncate.html) on each table they act on.

**Concrete example and logging output collected:**

Stack trace that occurs when the query that cleans up old compile reports, is cancelled:

```
Traceback (most recent call last):
  File "/tmp/inmanta-core/src/inmanta/data/__init__.py", line 1252, in _execute_query
    return await con.execute(query, *values)
  File "/tmp/inmanta-core/env/lib64/python3.9/site-packages/asyncpg/connection.py", line 320, in execute
    _, status, _ = await self._execute(
  File "/tmp/inmanta-core/env/lib64/python3.9/site-packages/asyncpg/connection.py", line 1659, in _execute
    result, _ = await self.__execute(
  File "/tmp/inmanta-core/env/lib64/python3.9/site-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/tmp/inmanta-core/env/lib64/python3.9/site-packages/asyncpg/connection.py", line 1711, in _do_execute
    stmt = await self._get_statement(
  File "/tmp/inmanta-core/env/lib64/python3.9/site-packages/asyncpg/connection.py", line 398, in _get_statement
    statement = await self._protocol.prepare(
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
	asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/inmanta-core/src/inmanta/server/services/compilerservice.py", line 509, in _cleanup
    await data.Compile.delete_older_than(oldest_retained_date)
  File "/tmp/inmanta-core/src/inmanta/data/__init__.py", line 3442, in delete_older_than
    await cls._execute_query(query, oldest_retained_date, connection=connection)
  File "/tmp/inmanta-core/src/inmanta/data/__init__.py", line 1252, in _execute_query
    return await con.execute(query, *values)
  File "/tmp/inmanta-core/env/lib64/python3.9/site-packages/asyncpg/pool.py", line 993, in __aexit__
    await self.pool.release(con)
  File "/tmp/inmanta-core/env/lib64/python3.9/site-packages/asyncpg/pool.py", line 855, in release
    self._check_init()
  File "/tmp/inmanta-core/env/lib64/python3.9/site-packages/asyncpg/pool.py", line 948, in _check_init
    raise exceptions.InterfaceError('pool is closed')
asyncpg.exceptions._base.InterfaceError: pool is closed
```

State of the locks in the database when the test suite hangs:

```
inmanta4610007640=# select datname, pid, application_name, state_change, wait_event_type, wait_event, state, query FROM pg_stat_activity;
      datname      |   pid   | application_name |         state_change          | wait_event_type |     wait_event      | state  |                                     
                                                          query                                                                                               
-------------------+---------+------------------+-------------------------------+-----------------+---------------------+--------+-------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------
                   | 3099923 |                  |                               | Activity        | LogicalLauncherMain |        | 
                   | 3099921 |                  |                               | Activity        | AutoVacuumMain      |        | 
 inmanta4610007640 | 3099980 |                  | 2022-07-08 07:57:58.41367+02  | Lock            | relation            | active | TRUNCATE project, code, unknownparam
eter, agent, agentinstance, agentprocess, compile, configurationmodel, dryrun, parameter, report, resourceaction, environment, notification, resource CASCADE
 inmanta4610007640 | 3100006 |                  | 2022-07-08 07:57:58.403579+02 | Client          | ClientRead          | active | DELETE FROM compile WHERE completed 
<= $1::timestamp with time zone
 inmanta4610007640 | 3100005 |                  | 2022-07-08 07:57:58.406418+02 | Client          | ClientRead          | idle   | ROLLBACK;
 inmanta4610007640 | 3100007 |                  | 2022-07-08 07:57:58.40925+02  | Client          | ClientRead          | idle   | COMMIT;
 inmanta4610007640 | 3100530 | psql             | 2022-07-08 08:55:39.196387+02 |                 |                     | active | select datname, pid, application_nam
e, state_change, wait_event_type, wait_event, state, query FROM pg_stat_activity;
                   | 3099919 |                  |                               | Activity        | BgWriterHibernate   |        | 
                   | 3099918 |                  |                               | Activity        | CheckpointerMain    |        | 
                   | 3099920 |                  |                               | Activity        | WalWriterMain       |        | 
```

The above-mentioned table shows that the query to cleanup old compile reports has the `wait_event` `ClientRead`, This indicates that the client didn't properly close the transaction. The TRUNCATE query on the other hand waits on the lock held by the Compile report cleanup query.

**Proposed solution:**

Shield the queries to the database from cancellation (See: https://docs.python.org/3/library/asyncio-task.html#shielding-from-cancellation)
