### ISSUE TITLE
Module V2 loading/packing issues

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#4799]
# Problem

Several related issues have been discovered, related to packaged V2 modules.

1. When packaging V2 modules, the modules folder becomes a sub folder of the `plugins` folder
2. When there are very many `cf` files, the `load_plugins` function becomes **very** slow, because iglob has to go over all the `cf` files and folders (see image below)
2. When there is a `py` file in the `model` folder, it is loaded in packaged form, but not when doing editable install
3. When a package, namespace package or module `model`exist in the plugins directory, this collides with the model folder created when packaging, in which case the packaging would fail because `shutil` refuses to move the directory if the destination already exists.

# Proposed solutions

## Don't use glob
- use os.walk instead (see comment below)

## Cache results
- make sure we don't walk the same tree twice 

## Ignore the model folder

- don't allow a python package to be called model
- don't load from this model package and don't glob into it
Evaluation:
- not very clean towards end users

## Pack an index file

- When packaging, include an index file that lists all python files, to use instead of glob
- Don't package py files from the model folder
- Make sure the models folder is merged cleanly if there is a models python package/module/namespace package
-> ignore this one for now, too difficult 

![image](https://user-images.githubusercontent.com/1788254/188630786-04dcd742-766e-44d7-a4f1-6b5ca6b30e8d.png)

**Comment by bartv** [comment]
```
>>> a=time.time(); _=glob.glob("**/*.cf", recursive=True); b=time.time(); print(b-a)
1.2613184452056885
>>> a=time.time(); _=list(os.walk(".")); b=time.time(); print(b-a)
0.6399760246276855
```

os.walk is much faster than glob.glob

Filtering out the correct files can be done with a simple expression:  `file[-3:]==".py"`

**Comment by wouterdb** [comment]
![image](https://github.com/inmanta/inmanta-core/assets/1788254/4da5e578-e45b-4bc1-b99b-2058798492c4)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/4799?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta

**Comment by wouterdb** [comment]
ask solutions team for a module (I think juniper)
