### ISSUE TITLE
Increment calculation causes strange artifacts in resources view

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#4864]
When the resources view is open while running a deploy it depends on the refresh interval what you see. It seems that only when the first agent pulls the resources, the increment is calculated and the resources are marked as deployed.

The result of that is that you go from a green bar to full grey (everything is marked as available) to a green bar again.

It is desirable that this is already done when the version is made available (promoted)

**Comment by wouterdb** [comment]
secondary, the increment cache is now only calculated when the first agent pulls. This causes the get_resource_for_agent to be slow.
