### ISSUE TITLE
Remove dashboard from release

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#4905]
In ISO6 the old dashboard should not longer be included. This means:

- [x] Removing it from the builds (RPM specfile + pyproject.toml in product repo)
- [ ] Removing the static file handler from the server
- [ ] Adding a redirecting from dashboard to console
- [ ] Remove the docs

Only in iso6 and OSS

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/4905?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
