### ISSUE TITLE
Add module and plugin deprecation mechanism

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#4908]
The goal of this ticket is to add a deprecation mechanism to core for modules and plugins. The proposal is to:

- [x] Add a deprecated boolean field to module.yml When this is set to true, the compiler should issue a deprecation warning when the module is imported
- [x] Add a deprecation and replacedby field to the @plugin decorator. When set to true it should print out a warning that the plugin is deprecated. When replaceby is set the message should also say something like `This plugin has been replaced by {replacedby}`

If the current code does not support unkown keyword arguments it is best to create a new decorator so that we do not make modules incompatible with older releases. Similar for the additional keyword in the module.yml If required we need to support it as well in ISO5.

ISO4 modules are not updated so that should not be an issue.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/4908?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr

**Comment by edvgui** [comment]
Small proposal to get one step further with this (in a way which I think would improve the usability overall):

- Instead of passing a string in `replaced_by`, pass directly the other plugin object.  The advantages I see:
    1. You are sure that whatever this `replaced_by` is referring to must exist, and if at some point it doesn't anymore (should not happen), we will notice it directly.
    2. You can still access the name and even the location of the plugin (the name is in `<the_function_object>.__name__` and might even be extracted by the `plugin` decorator, no idea about how that thing is implemented) to improve the warning message.
- Allow to overwrite/extend the warning message, with another field in the decorator (something like `message`)

**Comment by FloLey** [comment]
@edvgui 
For me the `message` argument is overkill:
The default deprecation warning will already tell that the module will be deprecated and the replace_by will give more information about this. I think this is all what is needed. Adding a custom message will in most cases result in 'less' info than what the decorator would build.

For the rest I'm not against it :)
