### ISSUE TITLE
Add soft and hard timeout on the retry_limited method

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#4968]
# Description
Add hard timeout multiplier for `retry_limited`, configurable through env var and/or pytest option. The idea would be to be able to set the hard limit a lot higher than the soft limit. The algorithm would be as follows:

* Stop waiting when the wait condition is met or when the hard timeout is reached
* Raise an exception at the end of the `retry_limited` method when it took longer than soft_limit to reach the wait condition.

The `retry_limited` method can then show error messages like:

* Timeout: Wait condition was met after X seconds, but soft limit was set to Y seconds
* Timeout: Wait condition was not reach after hard limit of X seconds

## Original description

In general we always use a timeout of 10 seconds on the `retry_limited` method. In some circumstances this timeout is too sharp. When a test case fails with a timeout, it's hard to find out whether the test case would hang indefinitely or whether the condition would have been reached when the limit was set just a little higher. To improve the error reporting of the `retry_limited` method, I would like to propose the idea to add a soft and a hard timeout on that method. The idea would be to set the hard limit a lot higher than the soft limit. The algorithm would be as follows:

* Stop waiting when the wait condition is met or when the hard timeout is reached
* Raise an exception at the end of the `retry_limited` method when it took longer than soft_limit to reach the wait condition.

The `retry_limited` method can then show error messages like:

* Timeout: Wait condition was met after X seconds, but soft limit was set to Y seconds
* Timeout: Wait condition was not reach after hard limit of X seconds

**Comment by sanderr** [comment]
I like this suggestion a lot!

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/4968?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
