### ISSUE TITLE
[iso6] drop default constructors

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#4984]
- [x] drop default constructors
- [x] drop redundant `EntityLike` ABC (move docstrings to `Entity` where appropriate). Drop `get_entity()` method and simply use the entity where it's currently used.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/4984?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
