### ISSUE TITLE
Collect and report metrics about the environment

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#5013]
The goal of this EPIC is to add support to the orchestrator to collect timeseries data about the state of the environment over time and adding an API endpoint to return the metrics for the frontend to show. (This is in contract to self metrics we report  to influxdb).

The server should provide an endpoint to the frontend to:
- Fetch a list of metrics
- Within a time interval
- The number of datapoints in the interval / the grouping interval

A number of values (for example the compile rate) will require a not to low resolution otherwise the rate will always be really really small. 

The available metrics are:

- lsm.service_count: The number of services. _Here only the last value is sufficient for the frontend._
- lsm.service_instance_count: The number of service instances over time, grouped per state label.
- orchestrator.compile_time: The average time to compile the model
- orchestrator.compile_waiting_time: The average time a compile request stays in the queue
- orchestrator.compile_rate: The rate of compile requests in the interval
- resource.agent_count: The number of agents, grouped per state
- resource.resource_count: The resource count over time, grouped per state.

**Comment by wouterdb** [comment]
Notes:

https://aws.amazon.com/blogs/database/designing-high-performance-time-series-data-tables-on-amazon-rds-for-postgresql/
