### ISSUE TITLE
implement module release command

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#5082]
Implement the `inmanta module release` command with the following semantics:
- without arguments, it expects a dev version `x.y.z.devx` and converts it to a stable version `x.y.z`. It commits, adds a release tag, then calls `inmanta module release --dev --patch` (described below).
- with the `--dev` argument it converts the current version to a dev version. It optionally accepts `--patch`, `--minor` or `--major`, defaulting to `--patch`. The command results in a dev version that is at least the requested bump ahead of the last version tag. The changelog should be updated accordingly (either add a new section or rename the current one depending on the type of bump that was done). The command should commit the changes. It should not add a git tag.

Similar logic for dev bumping with respect to a bump specifier and the latest tag is currently implemented in `irt.release.release`, which might be of use.

Make sure to take the following into account:
- It should be compatible with both v1 and v2 modules. In particular, v1 modules have tags directly in the version field while v2 modules have it in the `egg_info.tag_version` field in `setup.cfg`. The metadata objects in `inmanta.module` likely already contain all abstractions to interact with tagged versions for both module generations.
- It should not break for modules that have never been released yet (have no last version tag)

Afterwards notify the solutions team.

**Comment by bartv** [comment]
I also think dev versions should not get a git tag?

**Comment by sanderr** [comment]
I'll add that explicitly.
