### ISSUE TITLE
deprecate inmanta modules commit

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#5084]
In iso5 and iso6, deprecate the `inmatna module commit` command in favor of `inmanta module release`.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/5084?planning-poker) with Zenhub @FloLey @Hugo-Inmanta @sanderr
