### ISSUE TITLE
Ensure that API endpoint sort their results in a consistent way

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#5466]
Tasks:

- [ ] The [`project_list` endpoint](https://github.com/inmanta/inmanta-core/blob/b781ed5a27137b0372f5471f0ec60fb341f58faf/src/inmanta/server/services/projectservice.py#L133) doesn't sort the returned projects and environments in a specific way. This issue should ensure a proper sorting order.
- [ ] Similar issues may exists in other endpoints in inmanta-core and its extensions. This issue should make sure that all other endpoints sort their results in a consistent and meaningful way. Focus on the simple methods in `protocol/server/services/`.

**Comment by bartv** [comment]
Based on an initial check this is a list of endpoints that do not seem to sort at first sight. Maybe they still do in the data layer:

- methods.get_compile_queue
- methods.list_environments
- methods.list_settings
- methods_v2.environment_settings_list
- methods.list_params
- methods_v2.get_facts
- methods.list_projects
- methods_v2.project_list
- methods_v2.get_resource_events
