### ISSUE TITLE
Improve error message on missing import for plugins

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#5571]
When you use types from the model in a plugin you need to add the imports to model/_init.cf The current message you get is:

```
could not find type athonet_mpn::infra::switch::Host in namespace athonet_mpn (/home/bart/workspace/projects/athonet/athonet_mpn/inmanta_plugins/athonet_mpn/__init__.py:74:1)
```

This can be improved to suggest that import athonet_mpn::infra::switch is missing from model/_init.cf

**Comment by sanderr** [comment]
@bartv could you try this one too?

**Comment by bartv** [comment]
Same message as well
