### ISSUE TITLE
Prohibit attributes with the name id

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#5605]
**Context**

The json schema used to send attributes to the server in the `put_version` and `put_partial` endpoint uses the [`id` attribute](https://github.com/inmanta/inmanta-core/blob/971d2c6e29bb400b358a1a53d1138ac8734c093f/src/inmanta/server/services/orchestrationservice.py#L530) to indicate the resource id of the resource. Consequently, [it's not possible to export an attribute called `id` to the server](https://github.com/inmanta/inmanta-core/blob/971d2c6e29bb400b358a1a53d1138ac8734c093f/src/inmanta/resources.py#L374). But it is possible to define such an attribute in the model. This issue tries to achieve a consistent behavior between the compiler and the exporter.

**Tasks:**

- [ ] Don't allow an attribute with the name `id` to be used in the model.

**Question:** A similar issue exists for [other names](https://github.com/inmanta/inmanta-core/blob/971d2c6e29bb400b358a1a53d1138ac8734c093f/src/inmanta/resources.py#L191). Do we broaden the scope of this issue to these other names?

**Comment by sanderr** [comment]
I think this may be overly restrictive. Perhaps we can disallow it in `std::Resource` only?

**Comment by sanderr** [comment]
Isn't this a restriction only in the fields of the resource? i.e. you can't define `fields = ("id",)` but the `Resource` subentity can have an `id` attribute. If you want to expose it to the resource class you'll just have to map it. Therefore (assuming what I'm saying here is correct) I think this would be overly restrictive. What do you think?

**Comment by arnaudsjs** [comment]
I agree it's quite restrictive and it's also a breaking change, but I do think it will be easier for the end users when he rules are consistent from the model all the way to the resources. 

A related issue: Currently it's possible to set the `id_attribute` of a resource to `id`, while it's not possible to export an attribute called `id`. This is something that is hard to explain.

**Comment by arnaudsjs** [comment]
This ticket is replaced by inmanta/pytest-inmanta#367
