### ISSUE TITLE
Investigate agent shutdown sequence

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#5607]
The `Agent.stop()` method stops the thread pools (used in the Agent and the AgentInstance class) asynchronously by invoking the `shutdown(wait=False)` method on it. This way the `Agent.stop()` stop can return while the thread pool is still executing work. This can causes test cases to fail, because the agent and the server are not stopped in the correct order.

Tasks:

- [ ] Investigate why thread pools are stopped asynchronously.
- [ ] Discuss the possible solutions for this issue with the team and agree on a solution.
- [ ] Implement fix.

**Comment by sanderr** [comment]
Observed in the following cases:
- [rocky9_master.tests.test_server.test_cleanup_old_agents](https://jenkins.inmanta.com/job/integration-tests/job/pytest/2165/branch=master,os=rocky9/testReport/junit/rocky9_master.tests/test_server/test_cleanup_old_agents/)
- [fedora-latest_iso6-stable.tests.test_agent_manager.test_dont_start_paused_agent](https://jenkins.inmanta.com/job/integration-tests/job/pytest/2169/branch=iso6-stable,os=fedora-latest/testReport/junit/fedora-latest_iso6-stable.tests/test_agent_manager/test_dont_start_paused_agent/)
- [fedora-latest_master.tests.test_cli.test_pause_agent](https://jenkins.inmanta.com/job/integration-tests/job/pytest/2161/branch=master,os=fedora-latest/testReport/junit/fedora-latest_master.tests/test_cli/test_pause_agent/)
