### ISSUE TITLE
add symlink to make inmanta-initial-user-setup command available on server

### ISSUE THREAD

**Issue by FloLey** [inmanta/inmanta-core#5661]
We need to make sure that the RPMs add a symlink from the `/bin` directory of the server to the `inmanta-initial-user-setup` binary present in the `/opt/inmanta/bin/ `directory of the venv. Otherwise the `inmanta-initial-user-setup` command is not available in the PATH of the server.

**Comment by arnaudsjs** [comment]
We decided not to implement this, because the `inmanta-initial-user-setup` command is rarely used.
