### ISSUE TITLE
Expose core logging setup through the stable api

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta-core#5815]
As discussed here: https://inmanta.slack.com/archives/CKRF0C8R3/p1680678625072959

It would be nice to expose (at least some part) of the logging setup done by core through the stable api, to allow other python tools developed internally to reuse it.  Simplifying their development and making them more consistent with core.

The method which would be handy are:
```
inmanta.app._get_default_stream_handler()
inmanta.app._get_log_formatter_for_stream_handler(timed=True)
inmanta.app._convert_to_log_level(verbose)
```

**Comment by sanderr** [comment]
Special attention should be paid to naming and docstrings.

**Comment by edvgui** [comment]
- https://code.inmanta.com/solutions/tools/yang-module-generator/-/blob/master/src/yang_module_generator/cli.py#L77-97
- https://code.inmanta.com/solutions/modules/restbase/-/blob/master/inmanta_plugins/restbase/generator/app.py#L24-41
