### ISSUE TITLE
web-console environment delete does not delete env directories on server

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#5974]
Desired behavior:
- should delete the directory
- should return an error code if anything (e.g. delete because of root-owned files) goes wrong.

**Comment by sanderr** [comment]
To be confirmed. May just have been an issue with running e.g. pip install as root on the environment prior to delete.

**Comment by Hugo-Inmanta** [comment]
Current behaviour tested on iso6: http://192.168.2.38:8888:

Clicking on the `Delete environment` button
- **does not** delete var/lib/inmanta/server/environments/<env_id>
- http://192.168.2.38:8888/console/settings?env=<env_id> is no longer accessible


Clicking on the `Clear environment` button
- deletes var/lib/inmanta/server/environments/<env_id>
- http://192.168.2.38:8888/console/settings?env=<env_id> is still accessible
