### ISSUE TITLE
add dedicated pip index url config for full project

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#5993]
Follow-up for #5976.

- [x] deprecate package source config
- [x] introduce `pip: { index_url: str[] }` config option: applies to all the project's pip installs, not only v2
- [ ] Open question: what with agent installs?
- [ ] make sure pytest-inmanta etc still work + create follow-up tickets for migration to non-deprecated config
- [ ] update project template: also make sure there is no confusion on repo_url vs package_repo, renaming them and adding comments clarifying what they are and why they're there, then pointing to the docs.

**Comment by Hugo-Inmanta** [comment]
As discussed in planning meeting don't rename the options in the project template
