### ISSUE TITLE
Run tests on master against 3.11

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#6022]
Update tox on master to run against python 3.11

ISO6 stays on 3.9

- [x] core
- [ ] inmanta-lsm (need 3.11 wheels)
- [ ] inmanta-license (need 3.11 wheels)
- [ ] inmanta support (repo is still aligned with iso6, don't want to run iso6 against py3.11)
- [x] inmanta-ui

**Comment by sanderr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/6022?planning-poker) with Zenhub @FloLey @Hugo-Inmanta @wouterdb
