### ISSUE TITLE
Build RPMS against python 3.11

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#6024]
Build OSS and ISO7 rpms that use python3.11 on RHEL8 and RHEL9.

**Comment by sanderr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/6024?planning-poker) with Zenhub @FloLey @Hugo-Inmanta @wouterdb
