### ISSUE TITLE
Build containers for master using ubi[8-9]/python311

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#6026]
https://catalog.redhat.com/software/containers/ubi9/python-311/63f764b03f0b02a2e2d63fff

- Make sure this happens automatically in the future based on the product config, similar to how it's done for the el version
- apply this for iso and OSS
- make sure that master (on both repos) has el9 first in the list (first is used to build docker images)

**Comment by Hugo-Inmanta** [comment]
Closed by:
- https://github.com/inmanta/inmanta/pull/118
- https://github.com/inmanta/inmanta-service-orchestrator/pull/432
- https://github.com/inmanta/irt/pull/1769
