### ISSUE TITLE
[Potential bug] ResourceVersionId missing version.

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/inmanta-core#6220]
This could be a possible bug. 

The Web-console expects the resource_id to contain the version (just like in the error message) to be able to truncate the string to only keep the resourceId. Now it gets a string without the version information, causing the truncation to happen at the wrong comma section. This breaks the redirection when clicking in the diagnose page to go the the resource information. 

`/lsm/v1/service_inventory/basic-service/3fe6cb43-15ad-4054-99d4-468b9e23d94c/diagnose` is the endpoint called to retrieve this information below.

![image](https://github.com/inmanta/inmanta-core/assets/44098050/9b5e1c00-90c6-49f0-9cb7-9e8abd8ead44)

But when we do the `/lsm/v1/service_inventory/basic-service/3fe6cb43-15ad-4054-99d4-468b9e23d94c/resources?current_version=3`

we get 
```
{
    "data": [
        {
            "resource_id": "frontend_model::TestResource[internal,name=default-0005],v=4",
            "resource_state": "failed"
        }
    ]
}
```

The test in the FE expected this as the outcome from the truncation. 
![image](https://github.com/inmanta/inmanta-core/assets/44098050/c200e71b-f3e1-4571-bd87-f29acb3c0254)

**Comment by sanderr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/6220?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta
