### ISSUE TITLE
Clearly mention the required RHEL version in the install documentation

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#6324]
The install documentation should clearly mention the RHEL version that should be used for a specific ISO version. 

Question: Do we support multiple RHEL versions for one ISO version or do we want our customers to use a specific RHEL version, despite the fact that RPMs are available for multiple RHEL versions.

**Comment by sanderr** [comment]
Relevant information from duplicate ticket: if possible, update documentation without having to introduce a new major release task, e.g. irt could read pyproject.toml and set a variable in docs/conf.py that can then be used by the docs files in core.

**Comment by sanderr** [comment]
Conclusion from planning meeting: one version per iso version

**Comment by bartv** [comment]
Why? What do you propose that we recommend then? RHEL8 only? Because that is what our customers are using.

**Comment by sanderr** [comment]
Conclusion from Slack: support all versions mentioned in the [release schedule](https://docs.google.com/spreadsheets/d/1xAmG9i2pIOFLk1IVfdGqISgIEE_TdkQwCH45odzxt9U/edit#gid=0)

**Comment by sanderr** [comment]
Closing in favor of inmanta/irt#1921, which has a wider scope.
