### ISSUE TITLE
iso installation docs unclear on supported RHEL versions

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#6327]
The docs don't mention anywhere which RHEL versions are supported. More than that, there is some confusion on that within the team itself: we build RHEL 9 RPMs, does that mean we support it, or just that it might work? The documentation currently hardcodes RHEL 8 in the yum config file.

- [ ] find a concensus on which iso versions support which RHEL versions and how this will be going forward
- [ ] make sure documentation matches this, preferably without having to introduce a new major release task, e.g. `irt` could read `pyproject.toml` and set a variable in `docs/conf.py` that can then be used by the docs files in core.

**Comment by arnaudsjs** [comment]
This is a duplicate of https://github.com/inmanta/inmanta-core/issues/6324

**Comment by sanderr** [comment]
Right, we even talked about it, what was I thinking...

**Comment by sanderr** [comment]
closing as duplicate
