### ISSUE TITLE
link to API reference is relative

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#6338]
When you open the documentation for a module, then click "REST API Reference" in the tab to the left, it tries to navigate to `/reference/modules/openapi.html` instead of `/reference/openapi.html`.

**Comment by Hugo-Inmanta** [comment]
We currently use this trick to include openapi.html (a non-sphinx document) in a toc-tree:
https://stackoverflow.com/a/31820846

**Comment by sanderr** [comment]
https://github.com/inmanta/inmanta-core/blob/5222908a22beef410978ed2cdc5312280688c438/docs/reference/index.rst?plain=1#L20
