### ISSUE TITLE
Ensure release version is not executed twice

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#6349]
Currently, release_version does not check if the version is already released. 

We should make sure this method gets executed only once.

This may have a few implications:
- it is correctly not in a transaction, so it may take some extra work to make it not run while it is running
- if we change the return code, we may affect the front-end

**Comment by sanderr** [comment]
Discussed in planning meeting: make it return a 409 CONFLICT (give solutions team and frontend a heads up), see if any tests start failing. If fallout is unacceptable, revert and just return 200 when the release has already been done, ignoring the new request silently.

**Comment by sanderr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/6349?planning-poker) with Zenhub @FloLey @Hugo-Inmanta @wouterdb
