### ISSUE TITLE
longevity monitoring doesn't track compile results

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#6371]
It tracks deploy results but not compile results. 2023.2 has had failing compiles for quite a while without anyone noticing. See `longevity.py` in the integration repo.

- find API endpoint that return the desired information
- update `longevity.py` to periodically call this endpoint and report to influx
- add a grafana dashboard and alert on that data

**Comment by Hugo-Inmanta** [comment]
- Added grafana dashboard `Compile results` https://grafana.inmanta.com/d/12568463/longevity?orgId=1
- Added alert rule https://grafana.inmanta.com/alerting/grafana/da8c3e6c-0778-414d-9b2a-01b064596edf/view?returnTo=%2Falerting%2Flist
