### ISSUE TITLE
move minimal python version to Python 3.11

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#6372]
- [x] Run `pyupgrade` on iso6 and master to use 3.9 conventions, verify results. 
  -> PR with interesting discussion here https://github.com/inmanta/inmanta-core/pull/6696
- [x] Then try the same for 3.11 on master only, don't commit if it causes a lot of divergence. ask on slack if in doubt. 
- [x] bump the minimal python version on master to 3.11
  - [x] https://github.com/inmanta/inmanta/pull/122
  - [x] core -> Already done
  - [x] https://github.com/inmanta/inmanta-license/pull/571
  - [x] https://github.com/inmanta/inmanta-lsm/pull/1518 
  - [x] https://github.com/inmanta/inmanta-service-orchestrator/pull/447
  - [x] https://github.com/inmanta/inmanta-ui/pull/486
- [x] check typing-extensions imports and replace with typing imports where possible. Drop typing-extensions as dependency if appropriate.
- [x] make tickets for the other extensions to do the same
  -> https://github.com/inmanta/inmanta-core/issues/6819
- [x] add internal docs on how to run the tool:
  - https://code.inmanta.com/inmanta/developerdocs/-/merge_requests/137/diffs

**Comment by sanderr** [comment]
Wait for solutions team to give the go-ahead. Expected around end of August.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/6372?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
