### ISSUE TITLE
split environment delete in small transactions

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#6427]
Main motivation: decrease lock contention. Deletes can be performed top-up, without resorting to cascading delete, outside of a transaction so that only one lock is acquired per "transaction". For more details, see [the slides of the planning meeting](https://docs.google.com/presentation/d/1-XcL0-DYmWVHBoacLBLu9UrG8Zs5EHq5npBqFZO9aFM/edit#slide=id.g25dbdc8f3b5_0_0).

- code already exists in the clear environment path that doesn't rely on cascade deletes as much
- this code should be updated to rely on cascading deletes even less, especially when it comes to the resource action - resource join table
- the environment delete should use this code path
- afterwards, check deadlock situation and create follow-up tickets according to planning meeting slides

**Comment by arnaudsjs** [comment]
I would also consider cherry-picking this fix on the stable branches, since the "pytest in docker" Jenkins job regularly fails on deadlock issues.
