### ISSUE TITLE
Confusing compile time output

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#6480]
The output of the compiler contains the following:

```
$ inmanta -vvv compile
...
inmanta.execute.schedulerINFO    Total compilation time 0.004380
inmanta.compiler         DEBUG   Compile done
inmanta                  DEBUG   Compile time: 0.077 seconds
```

It logs `total compilation time` and `Compile time` with two different values. It's unclear what the difference is between both and the former doesn't have a unit associated. This ticket should improve this output.

**Comment by sanderr** [comment]
I think this is a duplicate of #6387, though it contains some more details. Could you confirm?
