### ISSUE TITLE
Improve error reporting in string formatters

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#6500]
Consider the following code:

```
entity Test:
end

implementation test for Test:
    std::print("This is test {{n}}")
    std::print(f"This is test {n}")
end

implement Test using test

Test()
```

It will report the error on the line of the implement statement and not the line where the formatter is located:

```
variable n not found (reported in implement __config__::Test using test when true (./test.cf:9:11))
```

**Comment by sanderr** [comment]
Does not seem to be specific to string formatters: any name lookup error in an implementation results in this behavior.
