### ISSUE TITLE
pip config: compiler side

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#6516]
Implement compiler side of the [pip config design](https://github.com/inmanta/designs/blob/master/modules/pip_config.md). Do not include changelog entries but if new breaking changes come to light, communicate them at #6518.

This requires meticulously reviewing the install and update path for both v1 and v2 modules

**Comment by wouterdb** [comment]
Changes wrt to design: 

# Pip Pre

>  pre: Optional[bool]: allow pre-releases when installing Python packages, i.e. pip --pre. If null, behaves like false unless pip.use-system-config=true, in which case system config is respected.

=> there is not option to disable `--pre` so if `pip.use-system-config=true` both `False` and None mean we use the system config
