### ISSUE TITLE
Setting up the orchestrator takes longer

### ISSUE THREAD

**Issue by LauraStordeur** [inmanta/inmanta-core#6520]
I noticed that we went back from 11seconds to 17-18 on Jenkins. Locally, it used to be around 6 seconds and is now also back to 11. 

[An example build](https://jenkins.inmanta.com/blue/organizations/jenkins/dashboard%2Fweb-console/detail/master/4275/pipeline)
![image](https://github.com/inmanta/inmanta-core/assets/44098050/da0024e5-2b66-4634-a607-274d0a4b01a1)

**Comment by sanderr** [comment]
Goal:
1. primary: investigate whether this is due to a change in the product, the container, or this specific setup. i.e. will this affect customers if we release it.
2. secondary: investigate concrete cause of the issue and fix it.

**Comment by bartv** [comment]
[Here](https://inmanta.slack.com/archives/C01QH7140NT/p1694771497633279) there is also discussion on potential slower performance, might be related
