### ISSUE TITLE
require environment pause before deletion

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#6587]
Currently an environment can be deleted at any time. It seems to me that since the deletion is non-atomic the orchestrator might start misbehaving. I think it would be better to only allow delete while the environment is paused. It should not be allowed to unpause an environment when a delete is in progress. The same for deleting an active model version.

**Comment by sanderr** [comment]
Conclusion from planning meeting:
- [ ] delete first halts the environment
- [x] clear just stops the agents (already implemented)
- [ ] environment can not be resumed while deleting
- [ ] reject deletion of active model version

**Comment by arnaudsjs** [comment]
This ticket should also makes the necessary changes to pytest-inmanta-lsm. Currently halting and clearing of an environment is configurable using config options. With this change in-place some of these combinations might not be possible anymore, when running against a sufficiently new version of inmanta-core
