### ISSUE TITLE
incorrect anchor for constructor with inferred namespace

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#6595]
When a constructor is called without an explicit namespace, relying on the namespace inference, the `TypeReferenceAnchor` it registers can not be resolved.

At construction of a `inmanta.ast.statements.generator.Constructor` object, it [registers a `TypeReferenceAnchor`](https://github.com/inmanta/inmanta-core/blob/17484701e1bf85722a59881444d4669907052749/src/inmanta/ast/statements/generator.py#L823C18-L823C18). This anchor contains the explicit namespace for the constructor call, but it is not aware of the [inference that happens at normalization time](https://github.com/inmanta/inmanta-core/blob/17484701e1bf85722a59881444d4669907052749/src/inmanta/ast/statements/generator.py#L865). Therefore the anchor will never successfully [resolve](https://github.com/inmanta/inmanta-core/blob/17484701e1bf85722a59881444d4669907052749/src/inmanta/ast/__init__.py#L253). This causes e.g. vscode to be incompatible with namespace inference.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/6595?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
