### ISSUE TITLE
f-strings don't support dict lookup

### ISSUE THREAD

**Issue by DariushMoh** [inmanta/inmanta-core#6625]
F-strings only expect simple variables to do string interpolation, the goal of this ticket is to add support for dict lookup.

For example:
```
t = {"name": "a"}
std::print(f"Dict value: {t['name']}")
```
This would output  `variable t['name'] not found (reported in std::print(Format(Dict value: {t['name']}))`

**Comment by sanderr** [comment]
I believe this is "just" a parser issue (see formatter example below). Try to fix it in the parser, report back if it turns out bigger than expected.

```ipython
>>> import string
>>> string.Formatter().format("test {hello} {hello[0]}", hello="world")
'test world w'
```
