### ISSUE TITLE
f-strings do not trim whitespace

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#6629]
The following code does not work:

```
data = 10
std::print(f"-> { data }")
```

```
Error: variable  data  not found (reported in std::print(Format(-> { data })) (./test.cf:5))
```

The lexer for these strings needs to extract the proper variable names!

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/6629?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
