### ISSUE TITLE
drop BigInt related option from inmanta-ui

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#6641]
The latest version of the web-console no longer uses this option. Think about compatibility before removing it.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/6641?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
