### ISSUE TITLE
Introduce env vars collection

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta-core#6732]
Create a constant/class/anything in the stable api, which exposes the environment variables that the server uses when communicating with:
- The compiler
- The agent?

The idea is to make is safe, easy and sytable to load env vars in error reporting, making sure that we don't log anything too noisy (inmanta user env vars) or too sensitive (credentials).

The request originates from [here](https://github.com/inmanta/lsm/pull/665#discussion_r1392165174), where we try to load all lsm-related env vars for debug in case of some helper function mis-usage.

**Comment by FloLey** [comment]
@edvgui this has been merged :)
