### ISSUE TITLE
Improve error message when installing module in editable mode

### ISSUE THREAD

**Issue by hlloreda** [inmanta/inmanta-core#6743]
I got this error when I tried to install a new module in editable mode.

![image](https://github.com/inmanta/inmanta-core/assets/32882487/6b749930-4021-47ba-99ac-c2b87575ce6e)

Adding more flags helps us find out what's causing the issue:

![image](https://github.com/inmanta/inmanta-core/assets/32882487/fc657ef3-4a7f-48c4-babf-34d372fbf03d)

But I think we should be able to figure out the source of the problem without adding these flags.

**Comment by sanderr** [comment]
Now that we've disabled/deprecated editable mode for this command, first task is to check if this is still an issue without editable mode.
