### ISSUE TITLE
discovery resources: allow matching by id

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#6779]
allow matching discovered resources with managed resources. The following should be supported for sure:

- include link to corresponding managed resource
  - should this include orphans? If so, should we mark them? Double check with Bart and Guillaume
  - this returns a new API column: can be achieved with join between discovered resource table and persistent state table, optionally including resource table depending on orphan decision.
- exclude managed resources from the discovered resources endpoint's return values (via API filter)
  - this is considered to be a filter associated with the column from the first bullet point
- notify frontend that this has been added

**Comment by Hugo-Inmanta** [comment]
> should this include orphans? If so, should we mark them? Double check with Bart and Guillaume

As discussed in standup Include orphans but don't specifically mark them as such
