### ISSUE TITLE
follow up pytest-asyncio breaking change

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#6848]
See pytest-dev/pytest-asyncio#713. This is blocking the bump of `inmanta-dev-dependencies`.

If no solution is provided upstream in a few days, ask for an update and/or create a workaround.

**Comment by wouterdb** [comment]
we will let this be for one week

**Comment by sanderr** [comment]
Upstream issue moved to pytest-dev/pytest-asyncio#729

**Comment by arnaudsjs** [comment]
The bugged version (0.32.3) has been excluded in the Dependabot version bump config: https://github.com/inmanta/inmanta-dev-dependencies/pull/363
