### ISSUE TITLE
longevity tests failing for newly released 2024.1

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#6853]
See [grafana](https://grafana.inmanta.com/d/12568463/longevity?orgId=1&var-endpoint=All&var-hosts=longevity-2024.1.ii.inmanta.com)

- [ ] shouldn't we get an alert for this? Where/how? The issue was fixed +- an hour after the first failure, so perhaps it just wasn't triggered yet?
- [x] investigate and fix

**Comment by wouterdb** [comment]
an alert was raised at 11
