### ISSUE TITLE
Log the version of the inmanta-server at startup

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#6866]

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/6866?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta

**Comment by wouterdb** [comment]
immediately at start (before DB is up)
