### ISSUE TITLE
Fix regression in optimized python file collection

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#6938]
#6882 optimized collection of Python files. Among other things it now only considers proper Python packages. As a result it skips namespace packages, which may, by accident or by design, be part of an inmanta module. e.g. this breaks modules who's developers were not aware that a package should have a `__init__.py` file.

- [ ] revert optimization (not entire PR, just the `__init__.py` part), replace it with a simple skipping of the `model` directory
- [ ] make sure `inmanta module build` raises a proper exception if the `model` directory already exists in `inmanta_plugins/mymodule/`. Currently it happens to raise an error when we call `shutil` so this is non-breaking.

**Comment by wouterdb** [comment]
imho we should not allow namespace packages below the top-level `inmanta_plugins` namespace package

**Comment by sanderr** [comment]
See [PEP 420](https://peps.python.org/pep-0420/#specification) for more details on implicit namespace packages.

**Comment by sanderr** [comment]
Conclusion from planning meeting:
- [ ] revert optimization, replace it with a simple skipping of the `model` directory
- [ ] make sure `inmanta module build` raises a proper exception if the `model` directory already exists in `inmanta_plugins/mymodule/`. Currently it happens to raise an error when we call `shutil` so this is non-breaking.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/6938?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
