### ISSUE TITLE
enable agent install of dependency modules by default

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#7026]
The `agent_install_dependency_modules` project option has to be set in all practical models. Therefore it would make sense to phase it out and enable its behavior by default. This requires a few extra steps to make it safe:

- [x] add documentation about inter-module dependencies: you can use them (no option required) but the module you depend on should not have any resources (technically it can iff they are always there but that's more difficult to explain so only mention that if the solutions team sees a use case for it). Otherwise you could get the following timeline:
1. `a` depends on `b`
2. exporter exports `a-1.0` and `b-1.0`, both of which have resources for this agent. Agent puts code in its code directory.
3. exporter exports `a-1.0` and `b-2.0`, `b` no longer has resources for this agent. Agent puts code for `a`, not `b` in its code directory but the old code for `b` is still there.
4. agent is restarted (also triggers without restart but unlike other code loading issues a restart doesn't solve it here): agent's module finder points to its code directory -> stale version of `b-1.0` is loaded instead of `b-2.0` installed by pip in the venv.

- [x] on the agent, before loading the code, detect the above scenario and add a warning log message and notification for it.

All of this is iso7+?

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/7026?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
