### ISSUE TITLE
improve performance of SourceInfo.get_siblings 

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#7040]
When running on larger modules, it seems that `SourceInfo.get_siblings ` in the code upload service causes significant load

![image](https://github.com/inmanta/inmanta-core/assets/1788254/5459383c-0dc3-4824-a820-6487aec45833)

We should investigate if this code can be made more efficient (I suspect we now search the same siblings over and over again)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/7040?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr

**Comment by sanderr** [comment]
May or may not be easier to call into `Module.get_python_files()`
