### ISSUE TITLE
Postgresql installation documentation for RHEL 9 is not working

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#7042]
Documentation: https://docs.inmanta.com/inmanta-service-orchestrator/7/install/1-install-server.html#step-3-install-postgresql-13

When I execute the command `sudo systemctl enable --now postgresql`, I get an error.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/7042?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
