### ISSUE TITLE
Database migration of #7238 seem to be unreliable

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#7263]
The DB migration on https://github.com/inmanta/inmanta-core/pull/7238

Seems to sometimes produce incorrect results 

https://app.slack.com/client/T02KH0H20/CKRF0C8R3

**Comment by arnaudsjs** [comment]
Something that is worth check is whether the scoping of the environment column is causing problems here. (I didn't verify this, it's just a potential root cause that crossed my mind). We can just as well alias everything:

```
INSERT INTO public.resource_persistent_state
 (environment, resource_id, last_deploy, last_success, last_non_deploying_status, last_produced_events)
 SELECT r.environment, r.resource_id, r.last_deploy, r.last_success, r.last_non_deploying_status, r.last_produced_events
 FROM public.resource AS r
 WHERE (r.environment, r.model) IN (
    SELECT c.environment, max(c.version) FROM public.configurationmodel AS c WHERE c.released=true GROUP BY c.environment
 );
```
