### ISSUE TITLE
add docs for user management

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#7357]
- [x] how to create initial user
- [ ] how to manage users through the UI

**Comment by arnaudsjs** [comment]
This ticket depends on: https://github.com/inmanta/web-console/issues/4738

**Comment by arnaudsjs** [comment]
The second part of this ticket, namely "how to manage users through the UI", will be added by the frontend team (See: https://inmanta.slack.com/archives/C045Y42N49W/p1711015970396729)
