### ISSUE TITLE
document the format used for reference to the api itself

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#7557]
# Problem

Currently, the notifications can carry links to compiles. 
We may also pass other links to the front-end, but it is unclear if and where.

The front-end must be able to dispatch these links to the correct page.

We should document all possible links we can emit, so they can handle them all.

**Comment by Hugo-Inmanta** [comment]
For reference, this PR https://github.com/inmanta/inmanta-core/pull/7543 adds another reference to the api:
- the `discovered_resources_get_batch` endpoint returns a link with format `"/api/v2/resource/<rid>"`
