### ISSUE TITLE
Add all modules to documentation

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#7580]
1. add the solutions set for every ISO to the docs
2. see if this still works (some modules are large)

# Note

Part of this has been done, notes are in the code on what is left to do

https://github.com/inmanta/irt/blob/master/sets/inmanta-service-orchestrator-8-docs.yml

**Comment by sanderr** [comment]
i.e. this page: https://docs.inmanta.com/inmanta-service-orchestrator/7/reference/modules.html
