### ISSUE TITLE
Inmanta uid/gid changed in latest container image

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta-core#7674]
With the latest release (24th of may 2024), the container images used another user id for the inmanta user.  This is an issue because:
1. This is not inline with documentation: https://docs.inmanta.com/community/latest/install/2-install-server-with-podman-and-systemd.html#start-the-server-with-systemd
2. This makes the update of a containerized orchestrator a lot more painful, as any mount owned by the inmanta user will now have the wrong ownership requiring manual repair.

This affects both oss and iso containers.

```console
guillaume@fedora-2:~$ podman run --rm -ti ghcr.io/inmanta/orchestrator:2024.2 cat /etc/passwd | grep inmanta
inmanta:x:993:993:Account used by the Inmanta daemons:/var/lib/inmanta:/usr/bin/bash
guillaume@fedora-2:~$ podman run --rm -ti ghcr.io/inmanta/orchestrator:2024.2.1 cat /etc/passwd | grep inmanta
inmanta:x:997:995:Account used by the Inmanta daemons:/var/lib/inmanta:/usr/bin/bash
```

**Comment by sanderr** [comment]
Conclusion from planning meeting: in the legacy dockerfile before installing the RPM, create the user and group with fixed id. Specfile already contains relevant commands, minus the hardcoded ids.
