### ISSUE TITLE
Fix agent cache

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#7696]
# Problem

1. The agent cache is now version based, this is complicated for end-users and becomes difficult in the new agent design
2. Time based expiry is broken: https://github.com/inmanta/inmanta-core/issues/833

# Proposed solution

1. we keep version open for a fixed time X (e.g. 1 minute after last use ended)
2. we generate a 'tick' to the cache regularly (e.g. 1s) to make it run finalizes), on a threadpool  (taking care not to race actual usage.

**Comment by sanderr** [comment]
Discussed in planning meeting. Main difficulty that needs to be addressed: discarding an entry from the cache means calling a custom finalizer, which is not async, therefore has to be run on a thread. It must only be called when the agent is not actively using the thing cached.

**Comment by sanderr** [comment]
See status [on Slack](https://inmanta.slack.com/archives/CKRF0C8R3/p1722611435774309)
