### ISSUE TITLE
Remove compiler venvs with out-dated Python version

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#7732]
When the server has been upgraded to a new Python version, the compiler server should re-create the compiler venvs. Up to now this was done by [a script](https://github.com/inmanta/inmanta/blob/186cf7b2fc99827c81900408bfd65aa2d11c20cf/inmanta.spec#L265) included in the RPM that would move the out-dated venv into a `.rpmsave` folder. The migration to native docker containers requires this functionality to move into the server itself.

Tasks:

- [x] Add the above-mentioned functionality to the compiler service.
- [ ] Remove the script from the RPM

Question: 

Do we rename the venvs like the RPM does or do we actually remove them?

**Comment by sanderr** [comment]
Discussed in planning meeting: concrete proposal:
- add python version to the directory name, e.g. `.venv-py312`
- symlink old name to the latest one
- add special-case for if the directory exists and is not a symlink => move it to appropriately named directory and symlink it. Create follow-up ticket to remove this in iso9.
