### ISSUE TITLE
Drop the `do` command

### ISSUE THREAD

**Issue by hlloreda** [inmanta/inmanta-core#7913]
The do command relies on shell to execute commands.  This makes us vulnerable, as it can execute arbitrary code based on user input (shell injection attacks).

Besides, this command doesn't seem to be used anymore

Related to https://github.com/inmanta/inmanta-core/pull/7908/files#r1694921680

**Comment by sanderr** [comment]
discussed in planning meeting: check with Wouter when he's back. If he agrees, drop on iso8.
