### ISSUE TITLE
Enforce usage of mypy-diff

### ISSUE THREAD

**Issue by hlloreda** [inmanta/inmanta-core#7927]
Currently, we don't enforce anything. 

Although it may not be feasible to rectify all existing issues, we must ensure that we do not introduce any new ones.
This can be done easily on the CI by ensuring that we do a `mypy-save` on the master branch and then checkout on the branch that needs to be tested.

**Comment by sanderr** [comment]
No longer relevant, we're now using mypy-baseline in the ci
