### ISSUE TITLE
Final api cleanup

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#8197]
- [x] Drop any api that used only by the old agent on the server 
- [x] Start stripping the underlying code , ticketize if stuck  
- [x] resource_Action_update, deploy_Start and deploy_done are to be investigated with care 
- [x] check the config option and env settings

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/8197?planning-poker) with Zenhub @arnaudsjs @hlloreda @Hugo-Inmanta @jptrindade

**Comment by arnaudsjs** [comment]
A follow up ticket was created to cleanup the documentation: https://github.com/inmanta/inmanta-core/issues/8429
