### ISSUE TITLE
Document server's on-disk layout.

### ISSUE THREAD

**Issue by Hugo-Inmanta** [inmanta/inmanta-core#8272]
Document the redesigned on disk layout introduced in https://github.com/inmanta/inmanta-core/pull/8220

Relevant [slack discussion](https://inmanta.slack.com/archives/CKRF0C8R3/p1730099795549499?thread_ts=1730098692.092579&cid=CKRF0C8R3)

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/8272?planning-poker) with Zenhub @arnaudsjs @hlloreda @Hugo-Inmanta @jptrindade @sanderr
