### ISSUE TITLE
possible race condition and blocking call in cache 

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#833]
The deletion process of the cache has two potential issues

- deletion is not under lock
- deletion is not necessarily run on the threadpool (when closing a version for example)

statements are potentially wrong

 with self.addLock:
                del self.addLocks[key]

(refactoring of cache is welcome)

**Comment by Hugo-Inmanta** [comment]
Adressed in https://github.com/inmanta/inmanta-core/pull/7846
