### ISSUE TITLE
Differentiate between skipped resources triggered by the default handler and skipped resources triggered by a custom handler

### ISSUE THREAD

**Issue by jptrindade** [inmanta/inmanta-core#8340]
Context: https://inmanta.slack.com/archives/CKRF0C8R3/p1730994402296499
# Eventual goal

- default handler skip would become a new exception type. This would be marked in the scheduler as (deployment_result=skipped, blocked=transient)
- custom handler skip would be raised as it is now. This would be marked in the scheduler as (deployment_result=skipped, blocked=no).

Why the difference? For the default handler skip we can make two assumptions:
- it does not make sense to retry until dependencies become successful
- it is possible that the resource may get deployed successfully later within this same model version (no new export required)

**Comment by sanderr** [comment]
Discussed in planning meeting: the new type of skip exception should also be available to raise by custom handlers, with a clear indication of what it means (transient based on dependencies' state).

**Comment by jptrindade** [comment]
Waiting for:
https://github.com/inmanta/inmanta-core/pull/8374
https://github.com/inmanta/inmanta-core/pull/8292
https://github.com/inmanta/inmanta-core/pull/8276

start with the part that is independent of the scheduler first (introduce the exception, raise it where appropriate, make sure it is correctly caught and propagated by the executors, i.e. that inmanta.deploy.tasks.Deploy.execute can see it.
