### ISSUE TITLE
bump PG version

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#8464]
PG16
- [x] udpate and test install docs
- [x] pyproject.toml in product repos
    - https://github.com/inmanta/inmanta-service-orchestrator/pull/537
    - https://github.com/inmanta/inmanta/pull/142
- [x] testing pipelines, unclear which / how exactly.
- [x] default on Jenkins runners (infra model?)
- [x] notify solutions team to update clab and docker-compose files
- [x] create page on the internal docs with overview of how to bump PG version (this list, corrected and prettified)

**Comment by edvgui** [comment]
For testing:
- Our lab will be updated next time they are restarted: https://code.inmanta.com/inmanta-infra/labs/-/commit/33191a9c476e0a6a9a57b42441dea474fa7cf986
- Containers created on the fly with pytest inmanta lsm will use the correct pg version: https://github.com/inmanta/pytest-inmanta-lsm/pull/469

**Comment by edvgui** [comment]
For infra:
- Changed default pg version in the infra model: https://code.inmanta.com/inmanta-infra/infra/-/commit/dbc6b3cde3b696e0139a9119b1d181ec42cc7df9

**Comment by edvgui** [comment]
https://internal.inmanta.com/development/core/checklists/move-to-new-pg-major
